// MCB_AVR_WDMioctl.h
//
// Define control codes for MCB_AVR_WDM driver
//

#ifndef __MCB_AVR_WDMioctl__h_
#define __MCB_AVR_WDMioctl__h_

#define MCB_AVR_WDM_IOCTL_START CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MCB_AVR_WDM_IOCTL_STOP CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MCB_AVR_WDM_IOCTL_CLEARSET CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MCB_AVR_WDM_IOCTL_SET CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MCB_AVR_WDM_IOCTL_MAP CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MCB_AVR_WDM_IOCTL_CLEAR CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define MCB_AVR_WDM_IOCTL_UNMAP CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif
